name: Coverage

on:
  push:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Test
        run: pnpm test

      - uses: codecov/codecov-action@v3
